// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC63wlL9Fbs3RVnUTlKaeOqCpi-Q1bBPig',
    appId: '1:472202407860:web:ae9e5325fd3d2a30070ce1',
    messagingSenderId: '472202407860',
    projectId: 'mangmentv103',
    authDomain: 'mangmentv103.firebaseapp.com',
    storageBucket: 'mangmentv103.firebasestorage.app',
    measurementId: 'G-0MPR5RLB1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDuKfEsWARnSoiDhiJJSPnQnJOnzoYNE0',
    appId: '1:472202407860:android:6fa7c78588078572070ce1',
    messagingSenderId: '472202407860',
    projectId: 'mangmentv103',
    storageBucket: 'mangmentv103.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfC-NhPYNOSA6UWQlmUBOwN_S0_KDIEgI',
    appId: '1:472202407860:ios:5b66201a712f2a55070ce1',
    messagingSenderId: '472202407860',
    projectId: 'mangmentv103',
    storageBucket: 'mangmentv103.firebasestorage.app',
    iosBundleId: 'com.example.mangmentv103',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfC-NhPYNOSA6UWQlmUBOwN_S0_KDIEgI',
    appId: '1:472202407860:ios:5b66201a712f2a55070ce1',
    messagingSenderId: '472202407860',
    projectId: 'mangmentv103',
    storageBucket: 'mangmentv103.firebasestorage.app',
    iosBundleId: 'com.example.mangmentv103',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC63wlL9Fbs3RVnUTlKaeOqCpi-Q1bBPig',
    appId: '1:472202407860:web:4227fba076255f3e070ce1',
    messagingSenderId: '472202407860',
    projectId: 'mangmentv103',
    authDomain: 'mangmentv103.firebaseapp.com',
    storageBucket: 'mangmentv103.firebasestorage.app',
    measurementId: 'G-TWNQ9P5CTN',
  );

}