name: mangmentv103
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  provider: ^6.1.4
  sqflite: ^2.4.2
  swipe_to: ^1.0.6
  table_calendar: ^3.2.0
  url_launcher: ^6.3.1
  firebase_auth:
  cloud_firestore: ^5.6.6
  android_intent_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/jpg/ 
